import pandas as pd
from datetime import datetime


df = pd.read_csv("data/exchange_rates.csv")

top_increase = df.loc[df["change"].idxmax()]
top_decrease = df.loc[df["change"].idxmin()]

main_currencies = df[df["currency_code"].isin(["USD", "EUR", "GBP"])]

report_date = datetime.now().strftime("%Y-%m-%d %H:%M")

report = f"""
Daily Exchange Rate Report
Generated by Flow Data Ops

Report generated at: {report_date}

Main Currencies:
"""

for _, row in main_currencies.iterrows():
    report += f"{row['currency_code']}: {row['exchange_rate']:.4f} | Change: {row['change']:.2f}%\n"

report += f"""

Strongest Increase:
{top_increase['currency_code']} increased by {top_increase['change']:.2f}%

Strongest Decrease:
{top_decrease['currency_code']} decreased by {top_decrease['change']:.2f}%

Insight:
The strongest movement today was in {top_increase['currency_code']}, while {top_decrease['currency_code']} showed the largest decline.

This report was generated automatically using Python, Pandas, and Bank of Israel public API data.
"""

with open("data/daily_exchange_rate_report.txt", "w", encoding="utf-8") as file:
    file.write(report)

print(report)
print("Report saved successfully.")